### ISSUE TITLE
View is not a binding layout (DialogController)

### ISSUE THREAD

**Issue by adin234** [esafirm/conductor-extra#6]
I extended from `BinderDialogController<T>()` but whenever i try to open my dialog, this error is being thrown
```
java.lang.IllegalArgumentException: View is not a binding layout
        at android.databinding.DataBindingUtil.bind(DataBindingUtil.java:180)
        at android.databinding.DataBindingUtil.bind(DataBindingUtil.java:152)
        at com.esafirm.conductorextra.databinding.DataBindingBinder$createBinder$1.bind(DataBindingBinder.kt:11)
        at com.esafirm.conductorextra.databinding.DataBindingBinder$createBinder$1.bind(DataBindingBinder.kt:9)
        at com.esafirm.conductorextra.components.BaseController$bindView$2.invoke(BaseController.kt:53)
        at com.esafirm.conductorextra.components.BaseController$bindView$2.invoke(BaseController.kt:11)
        at com.esafirm.conductorextra.ControllerExtKt$addLifecycleCallback$listener$1.preAttach(ControllerExt.kt:80)
        at com.bluelinelabs.conductor.Controller.attach(Controller.java:888)
        at com.bluelinelabs.conductor.Controller.access$500(Controller.java:44)
        at com.bluelinelabs.conductor.Controller$7.onAttached(Controller.java:1005)
        at com.bluelinelabs.conductor.internal.ViewAttachHandler.reportAttached(ViewAttachHandler.java:87)
        at com.bluelinelabs.conductor.internal.ViewAttachHandler.access$100(ViewAttachHandler.java:7)
        at com.bluelinelabs.conductor.internal.ViewAttachHandler$1.onAttached(ViewAttachHandler.java:47)
        at com.bluelinelabs.conductor.internal.ViewAttachHandler$2.onViewAttachedToWindow(ViewAttachHandler.java:126)
        at android.view.View.dispatchAttachedToWindow(View.java:18358)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5077)
        at android.view.ViewGroup.addView(ViewGroup.java:4865)
        at android.view.ViewGroup.addView(ViewGroup.java:4805)
        at android.view.ViewGroup.addView(ViewGroup.java:4778)
        at com.bluelinelabs.conductor.changehandler.AnimatorChangeHandler.performChange(AnimatorChangeHandler.java:126)
        at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:204)
        at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:154)
        at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:774)
        at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:744)
        at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:726)
        at com.bluelinelabs.conductor.Router.pushController(Router.java:179)
```

**Comment by adin234** [comment]
I was able to replicate this with the sample project

i updated the `DialogController` to use `DataBinding` and i received the same error

```
class DialogController : com.esafirm.conductorextra.databinding.BinderDialogController<DialogOntrollerBinding>() {

    @BindView(R.id.dialog_img) lateinit var imageView: ImageView

    override fun getLayoutView(container: ViewGroup): View =
            container.inflate(R.layout.dialog_ontroller)

    override fun onViewBound(bindingResult: DialogOntrollerBinding, savedState: Bundle?) {
        Picasso.with(applicationContext)
                .load("https://unsplash.it/200/300")
                .into(imageView)
    }
}
```

the error stack
```
2018-07-18 22:12:18.486 22207-22207/esafirm.com.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: esafirm.com.sample, PID: 22207
    java.lang.IllegalArgumentException: View is not a binding layout
        at android.databinding.DataBindingUtil.bind(DataBindingUtil.java:180)
        at android.databinding.DataBindingUtil.bind(DataBindingUtil.java:152)
        at com.esafirm.conductorextra.databinding.DataBindingBinder$createBinder$1.bind(DataBindingBinder.kt:11)
        at com.esafirm.conductorextra.databinding.DataBindingBinder$createBinder$1.bind(DataBindingBinder.kt:9)
        at com.esafirm.conductorextra.components.BaseController$bindView$2.invoke(BaseController.kt:55)
        at com.esafirm.conductorextra.components.BaseController$bindView$2.invoke(BaseController.kt:13)
        at com.esafirm.conductorextra.ControllerExtKt$addLifecycleCallback$listener$1.preAttach(ControllerExt.kt:98)
        at com.bluelinelabs.conductor.Controller.attach(Controller.java:888)
        at com.bluelinelabs.conductor.Controller.access$500(Controller.java:44)
        at com.bluelinelabs.conductor.Controller$7.onAttached(Controller.java:1005)
        at com.bluelinelabs.conductor.internal.ViewAttachHandler.reportAttached(ViewAttachHandler.java:87)
        at com.bluelinelabs.conductor.internal.ViewAttachHandler.access$100(ViewAttachHandler.java:7)
        at com.bluelinelabs.conductor.internal.ViewAttachHandler$1.onAttached(ViewAttachHandler.java:47)
        at com.bluelinelabs.conductor.internal.ViewAttachHandler$2.onViewAttachedToWindow(ViewAttachHandler.java:126)
        at android.view.View.dispatchAttachedToWindow(View.java:18358)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5077)
        at android.view.ViewGroup.addView(ViewGroup.java:4865)
        at android.view.ViewGroup.addView(ViewGroup.java:4805)
        at android.view.ViewGroup.addView(ViewGroup.java:4778)
        at com.bluelinelabs.conductor.changehandler.AnimatorChangeHandler.performChange(AnimatorChangeHandler.java:126)
        at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:204)
        at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:154)
        at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:774)
        at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:744)
        at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:726)
        at com.bluelinelabs.conductor.Router.pushController(Router.java:179)
        at com.esafirm.conductorextra.ControllerExtKt.showDialog(ControllerExt.kt:30)
        at com.esafirm.sample.MainController.onOptionsItemSelected(MainController.kt:96)
        at com.bluelinelabs.conductor.Controller.optionsItemSelected(Controller.java:1289)
        at com.bluelinelabs.conductor.Router.onOptionsItemSelected(Router.java:630)
        at com.bluelinelabs.conductor.internal.LifecycleHandler.onOptionsItemSelected(LifecycleHandler.java:271)
        at android.app.Fragment.performOptionsItemSelected(Fragment.java:2669)
        at android.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3183)
        at android.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:371)
        at android.app.Activity.onMenuItemSelected(Activity.java:3546)
        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:407)
        at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
        at android.support.v7.app.AppCompatDelegateImplV9.onMenuItemSelected(AppCompatDelegateImplV9.java:674)
        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
        at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
        at android.widget.AdapterView.performItemClick(AdapterView.java:318)
2018-07-18 22:12:18.486 22207-22207/esafirm.com.sample E/AndroidRuntime:     at android.widget.AbsListView.performItemClick(AbsListView.java:1159)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)
        at android.widget.AbsListView$3.run(AbsListView.java:4052)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2018-07-18 22:12:18.491 1826-2611/? W/ActivityManager:   Force finishing act
```

**Comment by esafirm** [comment]
@adin234 reproduced. Let me check
